services:

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy-manager
    restart: always
    ports:
      - "80:80" # http
      - "81:81" # administracion
      - "443:443" # https
    volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt
    depends_on:
      - app-backend
    networks:
      - red-cba

  servidor-bd:
    image: mysql:8.0
    container_name: servidor-bd
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: adso_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - red-cba

  app-backend:
    image: nicobell182857/adso-nginx-flask
    container_name: app-backend
    environment:
      FLASK_ENV: development
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: adso_db
    depends_on:
      - servidor-bd
    networks:
      - red-cba

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - red-cba

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    networks:
      - red-cba

networks:
  red-cba:
    name: red-cba
    external: true

volumes:
  mysql-data:
    name: mysql-data
  uptime-kuma-data:
    name: uptime-kuma-data
